// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peer/configuration.proto

package protos;

public final class Configuration {
  private Configuration() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnchorPeersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.AnchorPeers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    java.util.List<protos.Configuration.AnchorPeer> 
        getAnchorPeersList();
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    protos.Configuration.AnchorPeer getAnchorPeers(int index);
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    int getAnchorPeersCount();
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    java.util.List<? extends protos.Configuration.AnchorPeerOrBuilder> 
        getAnchorPeersOrBuilderList();
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    protos.Configuration.AnchorPeerOrBuilder getAnchorPeersOrBuilder(
        int index);
  }
  /**
   * <pre>
   * AnchorPeers simply represents list of anchor peers which is used in ConfigurationItem
   * </pre>
   *
   * Protobuf type {@code protos.AnchorPeers}
   */
  public  static final class AnchorPeers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.AnchorPeers)
      AnchorPeersOrBuilder {
    // Use AnchorPeers.newBuilder() to construct.
    private AnchorPeers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnchorPeers() {
      anchorPeers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AnchorPeers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                anchorPeers_ = new java.util.ArrayList<protos.Configuration.AnchorPeer>();
                mutable_bitField0_ |= 0x00000001;
              }
              anchorPeers_.add(
                  input.readMessage(protos.Configuration.AnchorPeer.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          anchorPeers_ = java.util.Collections.unmodifiableList(anchorPeers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Configuration.internal_static_protos_AnchorPeers_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Configuration.internal_static_protos_AnchorPeers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Configuration.AnchorPeers.class, protos.Configuration.AnchorPeers.Builder.class);
    }

    public static final int ANCHOR_PEERS_FIELD_NUMBER = 1;
    private java.util.List<protos.Configuration.AnchorPeer> anchorPeers_;
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    public java.util.List<protos.Configuration.AnchorPeer> getAnchorPeersList() {
      return anchorPeers_;
    }
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    public java.util.List<? extends protos.Configuration.AnchorPeerOrBuilder> 
        getAnchorPeersOrBuilderList() {
      return anchorPeers_;
    }
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    public int getAnchorPeersCount() {
      return anchorPeers_.size();
    }
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    public protos.Configuration.AnchorPeer getAnchorPeers(int index) {
      return anchorPeers_.get(index);
    }
    /**
     * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
     */
    public protos.Configuration.AnchorPeerOrBuilder getAnchorPeersOrBuilder(
        int index) {
      return anchorPeers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < anchorPeers_.size(); i++) {
        output.writeMessage(1, anchorPeers_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < anchorPeers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, anchorPeers_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Configuration.AnchorPeers)) {
        return super.equals(obj);
      }
      protos.Configuration.AnchorPeers other = (protos.Configuration.AnchorPeers) obj;

      boolean result = true;
      result = result && getAnchorPeersList()
          .equals(other.getAnchorPeersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAnchorPeersCount() > 0) {
        hash = (37 * hash) + ANCHOR_PEERS_FIELD_NUMBER;
        hash = (53 * hash) + getAnchorPeersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Configuration.AnchorPeers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Configuration.AnchorPeers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Configuration.AnchorPeers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Configuration.AnchorPeers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Configuration.AnchorPeers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Configuration.AnchorPeers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Configuration.AnchorPeers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * AnchorPeers simply represents list of anchor peers which is used in ConfigurationItem
     * </pre>
     *
     * Protobuf type {@code protos.AnchorPeers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.AnchorPeers)
        protos.Configuration.AnchorPeersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Configuration.internal_static_protos_AnchorPeers_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Configuration.internal_static_protos_AnchorPeers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Configuration.AnchorPeers.class, protos.Configuration.AnchorPeers.Builder.class);
      }

      // Construct using protos.Configuration.AnchorPeers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAnchorPeersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (anchorPeersBuilder_ == null) {
          anchorPeers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          anchorPeersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Configuration.internal_static_protos_AnchorPeers_descriptor;
      }

      public protos.Configuration.AnchorPeers getDefaultInstanceForType() {
        return protos.Configuration.AnchorPeers.getDefaultInstance();
      }

      public protos.Configuration.AnchorPeers build() {
        protos.Configuration.AnchorPeers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.Configuration.AnchorPeers buildPartial() {
        protos.Configuration.AnchorPeers result = new protos.Configuration.AnchorPeers(this);
        int from_bitField0_ = bitField0_;
        if (anchorPeersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            anchorPeers_ = java.util.Collections.unmodifiableList(anchorPeers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.anchorPeers_ = anchorPeers_;
        } else {
          result.anchorPeers_ = anchorPeersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Configuration.AnchorPeers) {
          return mergeFrom((protos.Configuration.AnchorPeers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Configuration.AnchorPeers other) {
        if (other == protos.Configuration.AnchorPeers.getDefaultInstance()) return this;
        if (anchorPeersBuilder_ == null) {
          if (!other.anchorPeers_.isEmpty()) {
            if (anchorPeers_.isEmpty()) {
              anchorPeers_ = other.anchorPeers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAnchorPeersIsMutable();
              anchorPeers_.addAll(other.anchorPeers_);
            }
            onChanged();
          }
        } else {
          if (!other.anchorPeers_.isEmpty()) {
            if (anchorPeersBuilder_.isEmpty()) {
              anchorPeersBuilder_.dispose();
              anchorPeersBuilder_ = null;
              anchorPeers_ = other.anchorPeers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              anchorPeersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAnchorPeersFieldBuilder() : null;
            } else {
              anchorPeersBuilder_.addAllMessages(other.anchorPeers_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Configuration.AnchorPeers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Configuration.AnchorPeers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<protos.Configuration.AnchorPeer> anchorPeers_ =
        java.util.Collections.emptyList();
      private void ensureAnchorPeersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          anchorPeers_ = new java.util.ArrayList<protos.Configuration.AnchorPeer>(anchorPeers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.Configuration.AnchorPeer, protos.Configuration.AnchorPeer.Builder, protos.Configuration.AnchorPeerOrBuilder> anchorPeersBuilder_;

      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public java.util.List<protos.Configuration.AnchorPeer> getAnchorPeersList() {
        if (anchorPeersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(anchorPeers_);
        } else {
          return anchorPeersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public int getAnchorPeersCount() {
        if (anchorPeersBuilder_ == null) {
          return anchorPeers_.size();
        } else {
          return anchorPeersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public protos.Configuration.AnchorPeer getAnchorPeers(int index) {
        if (anchorPeersBuilder_ == null) {
          return anchorPeers_.get(index);
        } else {
          return anchorPeersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder setAnchorPeers(
          int index, protos.Configuration.AnchorPeer value) {
        if (anchorPeersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnchorPeersIsMutable();
          anchorPeers_.set(index, value);
          onChanged();
        } else {
          anchorPeersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder setAnchorPeers(
          int index, protos.Configuration.AnchorPeer.Builder builderForValue) {
        if (anchorPeersBuilder_ == null) {
          ensureAnchorPeersIsMutable();
          anchorPeers_.set(index, builderForValue.build());
          onChanged();
        } else {
          anchorPeersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder addAnchorPeers(protos.Configuration.AnchorPeer value) {
        if (anchorPeersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnchorPeersIsMutable();
          anchorPeers_.add(value);
          onChanged();
        } else {
          anchorPeersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder addAnchorPeers(
          int index, protos.Configuration.AnchorPeer value) {
        if (anchorPeersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnchorPeersIsMutable();
          anchorPeers_.add(index, value);
          onChanged();
        } else {
          anchorPeersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder addAnchorPeers(
          protos.Configuration.AnchorPeer.Builder builderForValue) {
        if (anchorPeersBuilder_ == null) {
          ensureAnchorPeersIsMutable();
          anchorPeers_.add(builderForValue.build());
          onChanged();
        } else {
          anchorPeersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder addAnchorPeers(
          int index, protos.Configuration.AnchorPeer.Builder builderForValue) {
        if (anchorPeersBuilder_ == null) {
          ensureAnchorPeersIsMutable();
          anchorPeers_.add(index, builderForValue.build());
          onChanged();
        } else {
          anchorPeersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder addAllAnchorPeers(
          java.lang.Iterable<? extends protos.Configuration.AnchorPeer> values) {
        if (anchorPeersBuilder_ == null) {
          ensureAnchorPeersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, anchorPeers_);
          onChanged();
        } else {
          anchorPeersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder clearAnchorPeers() {
        if (anchorPeersBuilder_ == null) {
          anchorPeers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          anchorPeersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public Builder removeAnchorPeers(int index) {
        if (anchorPeersBuilder_ == null) {
          ensureAnchorPeersIsMutable();
          anchorPeers_.remove(index);
          onChanged();
        } else {
          anchorPeersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public protos.Configuration.AnchorPeer.Builder getAnchorPeersBuilder(
          int index) {
        return getAnchorPeersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public protos.Configuration.AnchorPeerOrBuilder getAnchorPeersOrBuilder(
          int index) {
        if (anchorPeersBuilder_ == null) {
          return anchorPeers_.get(index);  } else {
          return anchorPeersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public java.util.List<? extends protos.Configuration.AnchorPeerOrBuilder> 
           getAnchorPeersOrBuilderList() {
        if (anchorPeersBuilder_ != null) {
          return anchorPeersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(anchorPeers_);
        }
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public protos.Configuration.AnchorPeer.Builder addAnchorPeersBuilder() {
        return getAnchorPeersFieldBuilder().addBuilder(
            protos.Configuration.AnchorPeer.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public protos.Configuration.AnchorPeer.Builder addAnchorPeersBuilder(
          int index) {
        return getAnchorPeersFieldBuilder().addBuilder(
            index, protos.Configuration.AnchorPeer.getDefaultInstance());
      }
      /**
       * <code>repeated .protos.AnchorPeer anchor_peers = 1;</code>
       */
      public java.util.List<protos.Configuration.AnchorPeer.Builder> 
           getAnchorPeersBuilderList() {
        return getAnchorPeersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protos.Configuration.AnchorPeer, protos.Configuration.AnchorPeer.Builder, protos.Configuration.AnchorPeerOrBuilder> 
          getAnchorPeersFieldBuilder() {
        if (anchorPeersBuilder_ == null) {
          anchorPeersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protos.Configuration.AnchorPeer, protos.Configuration.AnchorPeer.Builder, protos.Configuration.AnchorPeerOrBuilder>(
                  anchorPeers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          anchorPeers_ = null;
        }
        return anchorPeersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.AnchorPeers)
    }

    // @@protoc_insertion_point(class_scope:protos.AnchorPeers)
    private static final protos.Configuration.AnchorPeers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Configuration.AnchorPeers();
    }

    public static protos.Configuration.AnchorPeers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnchorPeers>
        PARSER = new com.google.protobuf.AbstractParser<AnchorPeers>() {
      public AnchorPeers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AnchorPeers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnchorPeers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnchorPeers> getParserForType() {
      return PARSER;
    }

    public protos.Configuration.AnchorPeers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnchorPeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protos.AnchorPeer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * DNS host name of the anchor peer
     * </pre>
     *
     * <code>string host = 1;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     * DNS host name of the anchor peer
     * </pre>
     *
     * <code>string host = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <pre>
     * The port number
     * </pre>
     *
     * <code>int32 port = 2;</code>
     */
    int getPort();
  }
  /**
   * <pre>
   * AnchorPeer message structure which provides information about anchor peer, it includes host name,
   * port number and peer certificate.
   * </pre>
   *
   * Protobuf type {@code protos.AnchorPeer}
   */
  public  static final class AnchorPeer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protos.AnchorPeer)
      AnchorPeerOrBuilder {
    // Use AnchorPeer.newBuilder() to construct.
    private AnchorPeer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnchorPeer() {
      host_ = "";
      port_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AnchorPeer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.Configuration.internal_static_protos_AnchorPeer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.Configuration.internal_static_protos_AnchorPeer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.Configuration.AnchorPeer.class, protos.Configuration.AnchorPeer.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object host_;
    /**
     * <pre>
     * DNS host name of the anchor peer
     * </pre>
     *
     * <code>string host = 1;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * DNS host name of the anchor peer
     * </pre>
     *
     * <code>string host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <pre>
     * The port number
     * </pre>
     *
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.Configuration.AnchorPeer)) {
        return super.equals(obj);
      }
      protos.Configuration.AnchorPeer other = (protos.Configuration.AnchorPeer) obj;

      boolean result = true;
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.Configuration.AnchorPeer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Configuration.AnchorPeer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.Configuration.AnchorPeer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Configuration.AnchorPeer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.Configuration.AnchorPeer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.Configuration.AnchorPeer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.Configuration.AnchorPeer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.Configuration.AnchorPeer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * AnchorPeer message structure which provides information about anchor peer, it includes host name,
     * port number and peer certificate.
     * </pre>
     *
     * Protobuf type {@code protos.AnchorPeer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protos.AnchorPeer)
        protos.Configuration.AnchorPeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.Configuration.internal_static_protos_AnchorPeer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.Configuration.internal_static_protos_AnchorPeer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.Configuration.AnchorPeer.class, protos.Configuration.AnchorPeer.Builder.class);
      }

      // Construct using protos.Configuration.AnchorPeer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        host_ = "";

        port_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.Configuration.internal_static_protos_AnchorPeer_descriptor;
      }

      public protos.Configuration.AnchorPeer getDefaultInstanceForType() {
        return protos.Configuration.AnchorPeer.getDefaultInstance();
      }

      public protos.Configuration.AnchorPeer build() {
        protos.Configuration.AnchorPeer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protos.Configuration.AnchorPeer buildPartial() {
        protos.Configuration.AnchorPeer result = new protos.Configuration.AnchorPeer(this);
        result.host_ = host_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.Configuration.AnchorPeer) {
          return mergeFrom((protos.Configuration.AnchorPeer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.Configuration.AnchorPeer other) {
        if (other == protos.Configuration.AnchorPeer.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.Configuration.AnchorPeer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.Configuration.AnchorPeer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <pre>
       * DNS host name of the anchor peer
       * </pre>
       *
       * <code>string host = 1;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * DNS host name of the anchor peer
       * </pre>
       *
       * <code>string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * DNS host name of the anchor peer
       * </pre>
       *
       * <code>string host = 1;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * DNS host name of the anchor peer
       * </pre>
       *
       * <code>string host = 1;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * DNS host name of the anchor peer
       * </pre>
       *
       * <code>string host = 1;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <pre>
       * The port number
       * </pre>
       *
       * <code>int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <pre>
       * The port number
       * </pre>
       *
       * <code>int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The port number
       * </pre>
       *
       * <code>int32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protos.AnchorPeer)
    }

    // @@protoc_insertion_point(class_scope:protos.AnchorPeer)
    private static final protos.Configuration.AnchorPeer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.Configuration.AnchorPeer();
    }

    public static protos.Configuration.AnchorPeer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnchorPeer>
        PARSER = new com.google.protobuf.AbstractParser<AnchorPeer>() {
      public AnchorPeer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AnchorPeer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnchorPeer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnchorPeer> getParserForType() {
      return PARSER;
    }

    public protos.Configuration.AnchorPeer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_AnchorPeers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_AnchorPeers_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_AnchorPeer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_AnchorPeer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030peer/configuration.proto\022\006protos\"7\n\013An" +
      "chorPeers\022(\n\014anchor_peers\030\001 \003(\0132\022.protos" +
      ".AnchorPeer\"(\n\nAnchorPeer\022\014\n\004host\030\001 \001(\t\022" +
      "\014\n\004port\030\002 \001(\005B+Z)github.com/hyperledger/" +
      "fabric/protos/peerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_AnchorPeers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_AnchorPeers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_AnchorPeers_descriptor,
        new java.lang.String[] { "AnchorPeers", });
    internal_static_protos_AnchorPeer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_AnchorPeer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_AnchorPeer_descriptor,
        new java.lang.String[] { "Host", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
